### ISSUE TITLE
Dist-Zilla-Plugin-Test-NewVersion fails tests under _096, _097

### ISSUE THREAD

**Issue by karenetheridge** [Test-More/test-more#533]
I'm not sure if this is indicating a problem on your side or mine, but the depth of a test has now changed:

http://www.cpantesters.org/cpan/report/9b4b6760-9238-11e4-84ac-7af780f2ffb4

Also confirmed in the git repo:

```
: [ether@bourbon git/Dist-Zilla-Plugin-Test-NewVersion]$; perl -Ilib t/01-basic.t 
ok 1 - test created
ok 2 - no trailing whitespace in generated test
ok 3 - test checks the lib\/Foo\.pm module
ok 4 - test checks the lib\/Bar\/Baz\.pm module
ok 5 - test checks the lib\/Plack\/Test\.pm module
ok 6 - test checks the lib\/Moose\.pm module
ok 7 - test checks the lib\/Moose\/Cookbook\.pod module
# Subtest: running /Volumes/sake/git/Dist-Zilla-Plugin-Test-NewVersion/tmp/V1xhCR2lQR/build/lib...
    ok 1 - expected tests ran
    not ok 2 - our expected tests ran correctly
    #   Failed test 'our expected tests ran correctly'
    #   at t/01-basic.t line 76.
    # Compared $data->[0]{"depth"}
    #    got : '1'
    # expect : '2'
    1..2
    # Looks like you failed 1 test of 2.
not ok 8 - running /Volumes/sake/git/Dist-Zilla-Plugin-Test-NewVersion/tmp/V1xhCR2lQR/build/lib...
#   Failed test 'running /Volumes/sake/git/Dist-Zilla-Plugin-Test-NewVersion/tmp/V1xhCR2lQR/build/lib...'
#   at t/01-basic.t line 112.
1..8
# Looks like you failed 1 test of 8.
```

**Comment by exodist** [comment]
Now that I have had some time to glance at this, I have 2 things:

1) Depth checking was important with old Test::Builder, but is useless, and possibly harmless with new. I would recommend only caring about Depth on old builders, fact is the depth should not be something you have to worry about, it was unfortunate that the old builder made you do it.

2) For compatibility sake I do try to make sure the depth is still correct on the new builder. This is the only recent time I have seen one that was different. I suspect the issue is that loading the module via 'do' leaves the stack in such a place that the context object gets confused and takes a best guess. The solution will likely be to make that guessing account for this type of case. The effort is probably worth it, but I will also point out that this is the only known case broken :-)

**Comment by karenetheridge** [comment]
> Depth checking was important with old Test::Builder, but is useless, and possibly harmless with new.

Why is that? The depth is still significant, because that value is what determines the file and line number given as the source of the error.

**Comment by exodist** [comment]
The depth is not what you actually care about. The file and line number are. Depth is a terrible way to check for those. Far better to check them directly. 

Direct checking instead of depth is better in other ways as well, no need to update tests when you add a new layer in your code.

The new stuff makes it super easy to check what you actually care about directly.

**Comment by exodist** [comment]
Oh, should also note that depth is not how file+line number are determined exceot by legacy code. The modern way is to checkout a context at the right place. Everything deeper then finds the context.

**Comment by karenetheridge** [comment]
Here is the test file that the plugin generates.  In the failing test, you can just comment out everything that leads up to getting the test content, and replace it with this:

{{{
# this test was generated with Dist::Zilla::Plugin::Test::NewVersion <self>

use strict;
use warnings FATAL => 'all';

use Test::More 0.88;
use Encode;
use HTTP::Tiny;
use JSON;
use version;
use Module::Metadata;
use List::Util 'first';
use CPAN::Meta 2.120920;

# 'provides' field from dist metadata, if needed
my $dist_provides;

# returns bool, detailed message
sub version_is_bumped
{
    my ($module_metadata, $pkg) = @_;

    my $res = HTTP::Tiny->new->get("http://cpanidx.org/cpanidx/json/mod/$pkg");
    return (0, 'index could not be queried?') if not $res->{success};

    # JSON wants UTF-8 bytestreams, so we need to re-encode no matter what
    # encoding we got. -- rjbs, 2011-08-18 (in
    # Dist::Zilla::Plugin::CheckPrereqsIndexed)
    my $json_octets = Encode::encode_utf8($res->{content});
    my $payload = JSON::->new->decode($json_octets);

    return (0, 'no valid JSON returned') unless $payload;

    return (1, 'not indexed') if not defined $payload->[0]{mod_vers};
    return (1, 'VERSION is not set in index') if $payload->[0]{mod_vers} eq 'undef';

    my $indexed_version = version->parse($payload->[0]{mod_vers});
    my $current_version = $module_metadata->version($pkg);

    if (not defined $current_version)
    {
        $dist_provides ||= do {
            my $metafile = first { -e $_ } qw(MYMETA.json MYMETA.yml META.json META.yml);
            my $dist_metadata = $metafile ? CPAN::Meta->load_file($metafile) : undef;
            $dist_metadata->provides if $dist_metadata;
        };

        $current_version = $dist_provides->{$pkg}{version};
        return (0, 'VERSION is not set; indexed version is ' . $indexed_version)
            if not $dist_provides or not $current_version;
    }

    return (
        $indexed_version < $current_version,
        'indexed at ' . $indexed_version . '; local version is ' . $current_version,
    );
}

foreach my $filename (
    "lib\/Bar\/Baz\.pm",
    "lib\/ExtUtils\/MakeMaker\.pm",
    "lib\/Foo\.pm",
    "lib\/Moose\.pm",
    "lib\/Moose\/Cookbook\.pod",
    "lib\/Plack\/Test\.pm"
)
{
    my $module_metadata = Module::Metadata->new_from_file($filename);
    foreach my $pkg ($module_metadata->packages_inside)
    {
        my ($bumped, $message) = version_is_bumped($module_metadata, $pkg);
        ok($bumped, $pkg . ' (' . $filename . ') VERSION is ok'
            . ( $message ? (' (' . $message . ')') : '' )
        );
    }
}

done_testing;
}}}

**Comment by exodist** [comment]
Thanks, I will take a look during my next block of available time.

**Comment by exodist** [comment]
In legacy Test::Tester the depth was calculated by taking the number of stack frames between run_tests and the test itself, it would then adjust for level. In nearly all cases the desired result if for depth to be 1, when depth is not 1 it usually means you did something wrong. However in this case the main issue is the use of a subtest with a 'do' to run a file. This puts extra layers between run_tests and the tests, which is why the depth is not 1. Further Test::Tester simple does not support subtests, subtests reset $Level and do other fancy things Test::Tester just doesn't handle.

In new code $Level is no longer king, Context objects make determining the file+line of an error a much smarter exercise. As a result the events in this test will report to the correct files and lines. Test::Tester has been updated to be smart about this as well, which means with new code yoiu get the value you probably wanted, 1.

In any case, it appears this is not a Test-Simple problem. Please re-open if your investigation brings you back here :-)
