### ISSUE TITLE
perl build with AUTHOR_TESTING set fails cpan/Test-Simple/t/Legacy/ribasushi_diag.t

### ISSUE THREAD

**Issue by mohawk2** [Test-More/test-more#543]
To reproduce: set AUTHOR_TESTING then run perl's `make test`.

The code says:

```
    my $required = $ENV{AUTHOR_TESTING};

    if ($required && !$has_module) {
        die "This test requires 'SQL::Abstract::Test' to be installed when AUTHOR_TESTING.\n";
    }
```

Suggestion: also check for `$ENV{PERL_CORE}`.

**Comment by exodist** [comment]
Thanks. I think the best option is to not include that test in core. There are already a couple other tests we drop when we update core.

I will work on that for my next core patch.

**Comment by karenetheridge** [comment]
Just to clarify -- when you say "not include that test in core", do you mean
that the test will skip when `$ENV{PERL_CORE}` is set, or you will remove the
test entirely?

Adding an %ENV guard is going to be a lot easier for p5p maintainers than
dropping the test entirely -- that way, when a new Test::More release is made,
the files can be simply copied over into blead without any modifications.

**Comment by exodist** [comment]
I do mean literally not including the test file in core. There are several such test in Test-More already that are dropped, removing one more is fairly trivial. There is a script/config file used for importing Test-More into core that is used regularly, it is already smart enough to omit some files, I will update it to omit this one as well.

If this were a one off, or the first one of its kind I would simply adapt to $ENV{PERL_CORE} but since there is already a history and system in place to omit specific files, I will continue to follow the convention.

**Comment by exodist** [comment]
submitted a patch to perlbug to fix this issue.
