### ISSUE TITLE
Clarification needed on documentation/deprecation of Test::Builder interface

### ISSUE THREAD

**Issue by ribasushi** [Test-More/test-more#552]
I just noticed that Test::Builder [has been deprecated](https://metacpan.org/pod/release/EXODIST/Test-Simple-1.301001_098/lib/Test/Builder.pm#NAME). Most of the [documented methods](https://metacpan.org/pod/release/EXODIST/Test-Simple-1.301001_098/lib/Test/Builder.pm#EVENT-GENERATORS) (used [*extremely* widely](http://grep.cpan.me/?q=Test%3A%3ABuilder-%3Enew) in the wild) have had their documentation removed in lieu of a terse `Calling the methods below is not advised.`

Given that the old usage of the Test::Builder singleton functions as before, the justification for the `not advised` line is lost. I think a clear and tangible justification for the deprecation is warranted, especially given the downside of "brave new ways of doing things" as very eloquently described by @ap [in another thread](http://www.nntp.perl.org/group/perl.perl5.porters/2015/01/msg224811.html):

> (... newly proposed technique) is redundant with an existing
language feature that seems perfectly serviceable in maybe 99.9999% of
cases. All of these 99.9999% of users now have a non-backward compatible
option available to use in place of established syntax, even though for
them the choice makes absolutely no difference. This forks the ecosystem
along generational lines, with the side effect of creating an undertow
of enforced (= meritless) obsolescence. So new features have to justify
this fragmentation, at the very least by tangibly benefiting new users.

**Comment by ap** [comment]
Well, since I’m being quoted, let me add a few more points relevant to this particular occasion – despite, I have to qualify my opinion it, having only very cursorily skimmed the changes @ribasushi is talking about.

1. In Perl core in recent times [a distinction has been made things that are discouraged vs things that are deprecated](http://perldoc.perl.org/perlpolicy.html#Terminology).

   Things that are merely seen as bad practice may now be called out as discouraged, but they will not be deprecated for that reason alone. Nothing is deprecated unless it actively gets in the way of some other improvement, which itself has to justify itself on the basis of sufficient merit relative to the pain of its introduction. Deprecation now means that something is slated for removal (though it’s not an outright guarantee of removal).

   I think anyone maintaining a central piece of infrastructure should understand this difference and consciously make this distinction themselves.

2. *Even if* you deprecate something, you *never* simply remove the documentation for it.

   Reference documentation isn’t there to have an opinion on how users write code. Its most important function is as lifeline for the maintenance programmer who just had a piece of code dropped in their lap and who has no idea WTF it’s trying to do. In that situation, opening up the docs to find them saying nothing more than “don’t use this” is sure to make for one ruined day.

   Don’t do that. Don’t ruin that poor bastard’s day. Seriously, *don’t* do that.

   The way to make reference docs convey that something is discouraged is to make them say so right before explaining it. For every single discouraged item (e.g. every discouraged method); over and over. A maintenance programmer trying to get a grip on WTF is going on in some piece of code is only going to skim and point-dive the docs to the extent necessary to get a grip on the code in front of them; docs should be written to facilitate that mode of perusal.

   In fact this argues for keeping the docs even after the feature/method/whatever is actually gone, for at least some time.

**Comment by exodist** [comment]
First off, I will spend some time to make sure the documentation in Test::Builder is fully complete, I did not intend to leave it terse, and I did not intend to remove any important details.

That said the state the documentation was in meant I had to do something. While each method was maintained, and should still function identically as far as how to call it and what effect it has, the implementation details under the hood have changed.

Examples: The singleton is no longer the final destination and main hub for all results, most of the documentation assumed it was extremely misleading, if not outright lying with the new internals. Note, that is not to say any compatibility was broken, just that how the functionality was implemented was no longer correct.

In addition the layout of the Test::Builder documentation did not match up with all the new documentation that was being written. Reading the other module docs, then going to the Test::Builder docs was jarring at best. My goal is for the entire dist to have consistent and accurate information.

As for deprecated vs discouraged, that is good information, and I will evaluate my usage of each and make sure I am more accurate. There is a lot of stuff in Test::Builder I do want to deprecate with the hopes of eventually removing it, HOWEVER!!! I am very aware that the chances of getting the old code updated are so slim that I can't remove them for at least 150 years. So I WANT to remove them, but I recognize the reality that I probably never can.. That should not mean I cannot list things as something we WANT to remove if it ever becomes possible.

All methods should still have complete details, and full usage information, and enough for people to go on. If they don't then I failed, and I plan to fix it.

Finally, I ask that you do not attribute gaps in the docs to malice or intention, cause that is not the case.

**Comment by exodist** [comment]
Did not intend to close, as my commit message should show (for humans at least)

Anyway, @ribasushi please take a look at that and let me know where you think I fell short, I am sure you will find plenty of places that need better, or different docs. Please let me know here, I promise I will not close the ticket until we have at least a couple passes on this, or you tell me you are satisfied with the docs.

**Comment by ribasushi** [comment]
I won't be able to look at it myself until Thursday, due to a mini vacation. Just dropping a line that I eventually intend to read it, I just can't do it properly at this moment.

**Comment by exodist** [comment]
@ribasushi ping.

**Comment by ribasushi** [comment]
The fleshing out seems better than before. Please let me know if/when you ship this as another devrel, so I can peruse the cpan diff tools to check the docs against stable.

As a side note - this is not entirely correct: https://github.com/Test-More/test-more/commit/d15bd2440a7281d82601378dc77e6088d60cc37a#diff-e07e049db6ba650cd1605f4a5513b0ddR1236  A BAILOUT is interpreted by Test::Harness itself and stops **everything** including subsequent tests.

**Comment by exodist** [comment]
I was only documenting the behavior Test::Builder itself implements, not talking about the harness. The behavior is what you would see if the test was run directly with perl instead of prove. Test::Builder ALSO implements 'stop everything' on bail, but obviously only for the specific file that bailed. This behavior is legacy, not added by me,

**Comment by ap** [comment]
You have a point, @exodist. Though I can also see @ribasushi’s. Would it be reasonable to add just a parenthetical note that `BAIL_OUT` is *also* a signal to the harness? Something like this maybe?

> These will issue an L&lt;Test::Stream::Event::Bail> event (which signals the harness to skip any further tests).

**Comment by exodist** [comment]
Sure thing.

**Comment by exodist** [comment]
@ap note added (see reference above)

**Comment by ap** [comment]
Looks fine.

**Comment by dolmen** [comment]
This issue is still marked with the label "Blocking Stable". Is it still the case? @ap @ribasushi

**Comment by exodist** [comment]
This is no longer applicable. The change that caused this ticket has been reverted, the Test-More/Test-Builder docs have been restored to what they were before this ticket was an issue.

We will need documentation added that clarifies the Test2/Test::Builder relationship, but that is not critical at the moment.
