### ISSUE TITLE
Please add "nok" function

### ISSUE THREAD

**Issue by internationils** [Test-More/test-more#601]
Hello,
please add a "nok" function that os like "ok" but with "ne". I don't want the extra diagnostics that is/isnt offer, and don't want to have to pass stuff to testing routines to tell it to check for true or false. This would be a helpful addition.
Also: test groups would be helpful. I have a ton of tests that I can split into different routines etc., but allowing groups could be interesting.
Thanks
Nils

**Comment by internationils** [comment]
Sorry, I don't mean with "ne", but that tests for a false instead of a true result, and considers that a pass. So:
nok( 1==0; "Ensure that the universe obeys its basic laws"); # this should pass

**Comment by haarg** [comment]
Isn't this just "ok !"?

**Comment by exodist** [comment]
Can you elaborate on what you mean by groups? is it at all like subtests?

As for nok, if I did it i would add it as 'not_ok' but i don't think that is a good idea because of the way tap uses 'not ok' for a failed test. i think simply saying ok(!$thing) is sufficient, and less confusing. it is also shorter than typing 'not_ok()'.

**Comment by internationils** [comment]
Makes sense. I can live without a "not_ok" as I have a routine that I need to pass parameters to anyway, and then I can do a OK( (a eq b) == $truefalse; "Check as needed..."); I need to use OK because the stuff to be compared needs a Text::Diff::Table output to be readable if the test fails.

Re: groups. I have a parser that tests a bunch of things. Basic word parsing, comment parsing, quoted text parsing, line continuation, special characters, etc. with 3-8 tests each. I was thinking of doing $group = "Basic tests:"; ok(a eq b; "$group testing multiple words"); ... Looking at subtests seems to do pretty much that: 
subtest 'Testing the basics' => \&test_basic, $g;

Thanks for pointing me in the right direction and putting the work into the module! I'll close this issue.

**Comment by internationils** [comment]
Even nesting subtests works (as long as you count properly ;) ... I'm happy, thanks :)

**Comment by karenetheridge** [comment]
>  then I can do a `OK( (a eq b) == $truefalse; "Check as needed...");`

That would be better written as `cmp_ok($x, 'eq', $b, $testname)` -- but `is()` already does a stringwise comparison operation for you, so that would be more appropriate than manually using `eq`, generally.

>  I need to use OK because the stuff to be compared needs a Text::Diff::Table output to be readable if the test fails

You can always do this:

    sometestsub(...) or diag 'got this, rather than expected: ', explain $thing_I_got;

There are also deep-data-structure comparison routines available in Test::Deep and Test::Differences which dump the object in a readable fashion on failure.
