### ISSUE TITLE
Exotic test sequence fails with Test2-based Test::More

### ISSUE THREAD

**Issue by ribasushi** [Test-More/test-more#637]
Sorry for the late submission - this failure was not seen until now on my smoking setup due to... reasons (now fixed). While the test sequence might seem bizarre - it is distilled from a [real testcase](https://metacpan.org/source/RIBASUSHI/DBIx-Class-0.082821/t/51threads.t#L73-92) added [many years ago](https://github.com/dbsrgits/dbix-class/commit/a2f22854#diff-d78685a6d32aabb5cfec90984a5e560c). The issue is likely similar to https://github.com/Test-More/test-more/issues/549

Attached below is a standalone test (fails with latest, passes with stable):

```
use strict;
use warnings;
use threads;

use Test::More;

ok 1 for (1..2);

# used to reset the counter after thread finishes
my $ct_num = Test::More->builder->current_test;

my $subtest_out = async {
  my $out = '';

  #simulate a  subtest to not confuse the parent TAP emission
  my $tb = Test::More->builder;
  $tb->reset;
  for (qw/output failure_output todo_output/) {
    close $tb->$_;
    open ($tb->$_, '>', \$out);
  }
                                                                            
  ok 1 for (1..3);
                                                                            
  done_testing;

  close $tb->$_ for (qw/output failure_output todo_output/);

  $out;
}->join;

$subtest_out =~ s/^/   /gm;
print $subtest_out;

# reset as if the thread never "said" anything
Test::More->builder->current_test($ct_num);

ok 1 for (1..4);

done_testing;
```

**Comment by exodist** [comment]
Thanks for the report, taking a look.

**Comment by exodist** [comment]
Ok, I figured out why this happens. Test2 uses an IPC system to support threading/forking. When IPC is loaded (optional) all events are automatically sent to the root process/thread. Legacy Test::Builder turns on threading support if 'threads' is already loaded. The new Test::Builder does the same, the difference is that the IPC system is used as opposed to the old system of sharing a bunch of hash keys.

If you change the load order so that threads load AFTER Test::More then IPC is not loaded and the test passes exactly how it does on legacy.

So now we have this situation:
 * Test::More always loaded threading code if threads is loaded, I cannot change that
 * The new way of supporting 'threads' insures that events are sent to the right place
 * This test cannot pass because it relies on the old mechanism of thread support, which is to say it relies on Test::More not being smart enough to figure out it is in a different thread.

However there is an easy fix. Test::Builder->reset has always been a big hammer, and it always reset Test::Builders knowledge of the original pid to be the current pid. I am extending reset to make the current pid and thread id the ones the 'hub' thinks are original. This fixes the test sample.

I need to run my typical downstream tests to be sure this doesn't break anything, assuming it is good then this will be fixed next release.

**Comment by ribasushi** [comment]
Rest of ticket aside, this is troubling:

> This test cannot pass because it relies on the old mechanism of thread support

[This years-old explicit instruction](https://metacpan.org/pod/Test::More#Threads) translated to the institutional wisdom of *never load `threads` after `Test::More`*. In other words there are likely no thread-based tests that do not use the recommended load order. Your statements above seem to indicate you do not expect this to be the overwhelming case.

**Comment by exodist** [comment]
Whoah, I think there was a communication breakdown somewhere. If I even understand what you are suggesting then I can say for sure your interpretation, and assumptions of what I am thinking are wrong.

 * I am, and have always been aware that threads should be loaded before Test::More, and that everyone who uses threads will do so
 * I am not suggesting people change the load order, I was just noting that your test does pass if you swap the order. This is notable because it also still passes in legacy when you swap them, which is evidence that the code does not make use of Test::More's internal thread support.

This test passed on legacy because it depends on Test::More being very dumb with multi-threading. Test2 on the other hand is safer about threading, which is what broke this test. This test broke much the way a lot of old scripts do when 'use strict' is added.

That said, Test::More is old, and updating it cannot be allowed to break things except in very rare cases. This is not one of those rare cases, and I have already said I intend to fix it. I have a patch, but I am doing my due diligence in testing to be sure the patch doesn't cause new breakage.

**Comment by ribasushi** [comment]
Yeah, definitely miscomm.

> I am not suggesting people change the load order, I was just noting that your test does pass if you swap the order.

This statement is still quite puzzling to me, however...

>  I have a patch, but I am doing my due diligence in testing to be sure the patch doesn't cause new breakage.

...all is well given that \o/

**Comment by exodist** [comment]
^ The above patch has been used with my downstream testing and no issues were found. That said, I am going to let it sit in git for a bit, and give you and anyone else a chance to double-check the commit before I put it out in a new dev release.

-Chad

**Comment by ribasushi** [comment]
Excellence. Minimal local testing shows no issues. If a devrel containing this is made available, I can do much more extensive testing towards the end of the day.

**Comment by exodist** [comment]
in that case a dev release will be done shortly so that you can test it

**Comment by exodist** [comment]
http://metacpan.org/release/EXODIST/Test-Simple-1.302013_013

**Comment by exodist** [comment]
oops, did not make the test skip when threading is not available.. need a new release

**Comment by exodist** [comment]
https://metacpan.org/release/EXODIST/Test-Simple-1.302013_014

**Comment by ribasushi** [comment]
That seems to have taken care of things, cheers!

**Comment by exodist** [comment]
@ribasushi please see https://github.com/Test-More/test-more/commit/e5bbf57d6593c54dc97ce055c40fa09a79478566 which corrects a bug in the original fix. The bug was hidden by a race condition that only started triggering in an experimental branch.  Not sure if you are seeing any sporadic issues because of it.

**Comment by ribasushi** [comment]
Haven't experienced issues in my actual test, as my "waiting parent" does not "say" anything during the child thread's lifetime. So there's no opportunity for a race.

As far as the changeset goes - I can't meaningfully review it, as I've swapped the entirety of the T2 context out of mind. But if it works - it works ;)
