### ISSUE TITLE
t/zzz-check-breaks.t should use Test2::API::Breakage

### ISSUE THREAD

**Issue by dolmen** [Test-More/test-more#643]
t/zzz-check-breaks.t is currently based on parsing MYMETA/META. It requires CPAN::Meta, CPAN::Requirements and Module::Metadata, but the test is simply skip if one of those is not installed.

It would be better to use the information available in Test2::API::Breakage to avoid the CPAN::Meta prereq.
The Module::Metadata dependency could also be removed by just using `require`. Because we are not checking the $VERSION of any random module (which Module::Metadata is good at), but instead we will check $VERSION of a short known list of modules with known loading behaviors.

**Comment by exodist** [comment]
I had a test file like the one you mentioned. The problem is that loading the broken modules causes a lot of problems. I was able to get around most using eval and intercepting events, but at least one of the modules segv's if you load it, there is no good way to trap that. As a result I dropped my test in favor of the check-breaks method.
