### ISSUE TITLE
Test2 is not indexed but people already depend on it

### ISSUE THREAD

**Issue by andk** [Test-More/test-more#649]
The PAUSE indexer has abandoned all records about Test2 on April 25, the day when E/EX/EXODIST/Test2-0.000042.tar.gz got removed. Now we have packages that are untestable because they rely on Test2. It's not possible anymore to ask metacpan about reverse dependencies on Test2 because it's officially inexistent. As a proxy I take Test2::Suite, it still can be queried on metacpan. At least these distros are affected because they depend on Test2::Suite which in turn depends on Test2, so they are all devaluated:

``` text
Scientist-0.008
Test-Alien-0.06
Test-Script-Async-0.02
Test2-AsyncSubtest-0.000014
Test2-Tools-EventDumper-0.000006
WWW-LetsEncrypt-0.002
Trace-Mask-0.000007
Test2-Workflow-0.000006
Test2-Plugin-SpecDeclare-0.000001
App-Inspect-0.002
Export-Declare-0.002
```

All these and all their dependencies are currently completely ignored by cpantesters, so do not expect that the results of cpantesters will be representative. One may call cpantesters way of doing things stupid, but that's how it is today and we have to deal with it. If a dependency is inexistent, no reports are sent, the reports are dropped as invalid. I do not even find this stupid, it's just a self-defensive method of avoiding churn.

Is it unfair to ask, did packaging have to change so short before the announced release? Why did a release have to be announced before testing has gone through enough weeks? Why did nobody delay the announced release after the eight additional releases since 1.302014_001?

I'm not saying, the release must be stopped. But it's not evident to me how the data we produce on cpantesters could be considered sufficient for drawing conclusions.

**Comment by exodist** [comment]
I did not intend to remove the last Test2 tarball, I will get one back up.

The new releases are mostly changes to documentation, or to metadata, not logic or back compat. The few logic changes were incredibly minor.

**Comment by exodist** [comment]
Test2-0.000043 has been uploaded, sorry about that.

"after the eight additional releases since"  I feel that this phrasing, or even this way of looking at it is problematic. What if instead of releasing for every minor change I waited until they added up and just released _002 yesterday? It would be the same delta, but some of the changes would have less waiting, yet to anyone who is simply counting dev releases it would be less scary.

I figure releasing a new dev version for every minor change, even doc changes, helps insure we get every last minute of testing we can. Release early, release often. The content of these changes is almost all meta-data. There were 2 bugs fixed as well, but neither is a show-stopper, and only 1 effected anything in production (that we know about) and it was such a crazy edge case I don't think many people would be worried about it.

The announcement came to insure people would not be surprised by the release, and would have time to check their stuff. If I announced the day I was releasing that could be problematic to people who need/want a warning.

**Comment by andk** [comment]
Super, thanks for uploading 0.000043, I can already test Test::Alien again, and the first test is a pass.

Back to my rant. What I was saying was focussed on testing and the time that is needed for it. Release early, release often is very, very good, but only if there is no in advance fixed release date for the stable version. Testing makes only sense if there is a time window guaranteed to the testing resources to do (1) the testing itself and (2) wade through the data. By saying, the release date will be the 6th of May, the time window vanishes.

No, I'm absolutely happy to see your productivity and do not mind zillions of releases, there is nothing wrong about it. But please consider that testing needs time after the coders have finished.

The ideal time frame for a release procedure, IMO, is:

arbitrarily many dev releases;

followed by few release candidates; when RC-testing starts, an announcement is due, but read on why a fixed release date cannot be given at this point in time;

each release candidate gets the guarantee of a fixed amount of time that is considered enough for testing; a new release candidate or an otherwise raised doubt about the testing so far resets the timer; when we find out that our testing was invalid due to Test2 having gone lost on CPAN, it's a backlash, I'm not sure how much of a backlash, but to a certain degree, time must be reset;

the stable release happens when both the time was guaranteed and the result is good without doubt;

I'm aware that in reality people prefer to cheat around this ideal. So what, it's a gamble. It's the attitude that makes the difference. I prefer a CPAN that is perceived by the wider audience as a good and safe place to live. I believe we can achieve this by scrutiny rather than by a fixed time schedule.

**Comment by exodist** [comment]
I can appreciate your viewpoint. Right now the 6th is a week out. I will commit to resetting the clock if I have the need to make a new release between now and then.

If enough people come to me asking to have a longer timeline than a week between dev and stable then I am not dead set against extending it.

**Comment by andk** [comment]
Thanks! Feel free to close this ticket, since 0.000043 has resolved the immediate problem.
