### ISSUE TITLE
Test::Builder::Tester does not handle plan well

### ISSUE THREAD

**Issue by exodist** [Test-More/test-more#667]
Test::Builder::Tester has never done anything special in regard to plans. This means that TBT inherits any plan already set when you use it. It also means any plan set while TBT is in effect is kept by Test::Builder. This causes several problems:

#662 was exposed by the Test2 change, but was always a hidden land mine.

Here is another one:
https://github.com/chiselwright/test-dbix-class-schema/commit/f2674ebf40045364158178b9f04934b41beab564#diff-b53e22e7c3129bd13b8689b7d3930f69R55

24715a3e188912f1a6c690daa7cf5d1153c91ad1  is a fix for Test::Builder::Tester, but I reverted it in e6a2b63c3676767874a319602f093a753b6d939a  because it breaks things that either work around the problem, or expect the bug in other ways.

**So, what to do?**

 * Fix the bug, and notify people who's dists break from the fix.
 * Don't fix it, document it and maintain the current state so we don't break things that expect the bug.

#662 can be fixed with a simple change to TB->no_plan, whcih I plan to do seperately. This ticket is specific to TBT's handling of plans.

**Comment by kentfredric** [comment]
It would be preferable IME, given we've not had a lot of time to fix this bug in the wild, that we don't break things until we can implement a progressive solution.

Ideally, we should have a way to identify mis-use of the Test::Builder::Tester combination that causes this, and emit a warning from the top level to allow people to know that their code *may* be broken by future changes. ( That is, instead of considering this a bug from Test2/Test::Simple, consider this a bug from Test::Builder::Tester )

Obviously, it has to be done at a high enough level that this message circumvents the normal data channel that the user is testing, so that it emits to test output, and doesn't cause a subsequent failure due to warning.

It may not be possible to proceed in this way, but we should explore this option in depth first.

**Comment by exodist** [comment]
oops, closed wrong issue

**Comment by exodist** [comment]
At this point I think fixing this is more trouble than it is worth both for us and downstream. I have put up a PR that documents the problem and recommends Test2::API::Intercept.
