### ISSUE TITLE
Devel::INC::Sorted

### ISSUE THREAD

**Issue by frioux** [Test-More/test-more#715]
Devel::INC::Sorted had to be patched to work with Test2; would probably be worth fixing to make Test2 not break other modules that might do the same thing.  (https://metacpan.org/changes/distribution/Devel-INC-Sorted#L3)

**Comment by exodist** [comment]
can you make it more clear what exactly we broke?

**Comment by frioux** [comment]
https://github.com/karenetheridge/Devel-INC-Sorted/commit/eee6b42adf241ef68a9d83dbdfb01e653afccc45

**Comment by exodist** [comment]
Ah, the problem was that we changed how we use Exporter so that Exporter::Heavy is no longer loaded.

I do not consider this a bug. We intentionally avoid loading Exporter::Heavy because it dramatically increases test load times, and does not do anything for us.

In this case the bug was that something relied on Test::More to load dependencies instead of loading them itself. I don't consider this to be a bug we need to solve. We need to be free to stop using dep modules so long as doing so does not change our API.
