### ISSUE TITLE
Data::Peek

### ISSUE THREAD

**Issue by frioux** [Test-More/test-more#716]
Data::Peek had to be fixed to work with Test2 (https://metacpan.org/changes/distribution/Data-Peek#L8) would probably be worth fixing Test2 to not break other modules that do the same thing.

**Comment by exodist** [comment]
I remember this one. I submitted the fix to Tux. We ended up fixing this on the Data::Peek end because it is simply not possible to fix this on Test2's end. The test relied on internal state that can only be accessed via XS, and was always fragile, Test2 was just the first change to break it, not the only one capable of doing so, any number of deps can easily break that test.

Tux agreed that in this case it was not Test2's problem, that test is simply fragile.
