### ISSUE TITLE
Test-Simple-1.302086.tar.gz File-System Access Denied

### ISSUE THREAD

**Issue by Carlos314** [Test-More/test-more#783]
Hello,

      When I was downloading Test-Simple-1.302086.tar.gz, in browser displays the message "File-System Access Denied.

      Could you help me?, please

      Regards, Carlos

**Comment by jkeenan** [comment]
By any chance are you using Windows?

I ask because when I plugged your error message into DDG, most of the hits pertained to Windows.  (https://duckduckgo.com/?q=File-System+Access+Denied&t=canonical&ia=web).

I doubt this has anything to do with the Test-Simple tarball.  I recommend you first explore that error message.  Then, should you still need assistance, continue in this Issue by posting the output of ``perl -V`` for your system.

Thank you very much.
Jim Keenan

**Comment by exodist** [comment]
Closing this issue until evidence that this is actually a Test-Simple issue comes up.
