### ISSUE TITLE
shmread() errors from API/Instance.pm

### ISSUE THREAD

**Issue by FGasper** [Test-More/test-more#815]
http://www.cpantesters.org/cpan/report/2ca97cba-a504-11e8-95fc-e8aa660a1d5b
^^ I’m reasonably sure that the above failures aren’t from Linux::Perl itself. I can load FailWarnings with `-allow_deps => 1`, but I thought I’d report the error here, too.

**Comment by exodist** [comment]
@FGasper That is strange. I suspect it was actually a temporary configuration issue on the tester box. That SHM code is exercised quite thoroughly in the Test-Simple tests, and just about any other module on cpan. This is the only case of this error I have seen. 

If this comes up again, or continues to happen please re-open this ticket.

**Comment by eserte** [comment]
This warning happens quite often, but probably it's mostly not fatal. I just grepped in the December reports generated on my boxes:
```
$ grep -r 'SHM Read error' . | wc -l                                                                                                                                                                                       
     691
```

**Comment by eserte** [comment]
Here's a fresh one for BINARY/Cache-RedisDB-0.12.tar.gz:
```
#   Failed test 'Test::FailWarnings should catch no warnings'
#   at t/cache.t line 113.
# Warning was 'SHM Read error: Invalid argument' at /opt/perl-5.28.1/lib/site_perl/5.28.1/Test2/API/Instance.pm line 377.
...
```
(ubuntu18.04, perl 5.28.1)

**Comment by FGasper** [comment]
Another one: http://www.cpantesters.org/cpan/report/1b8e8db6-fbfe-11e8-bb7c-c0e617e67b24

**Comment by exodist** [comment]
I am working on a patch for this. This is a warning of a harmless problem with optimization, signaling that the optimization failed. There is nothing fatal about the optimization failing, so I will remove the warning.

**Comment by Leont** [comment]
> That SHM code is exercised quite thoroughly in the Test-Simple tests, and just about any other module on cpan. This is the only case of this error I have seen.

It appears that this only happens in modules that use Test::SharedFork, which is decidedly less tested. And clearly it's only happening some of the time.

> This is a warning of a harmless problem with optimization, signaling that the optimization failed. There is nothing fatal about the optimization failing, so I will remove the warning.

I'm worried that the underlying problem is actually real.

That error suggests that the shared memory segment no longer exists, which I think means the primary Test2 process doesn't exist anymore, which may mean that some of the test results aren't processed by that main process. I may be missing something though. Or is there a different explanation that isn't obvious to me?

**Comment by exodist** [comment]
There are other protections in place to notice if the primary test process exits before the others, if that were the real problem I would expect things to get a lot more noisy.

That said, I was under the impression that this error meant SHM was not working at all at any point in the test run so it was just being noisy. If that is not the case then this issue may not be resolved after all.

**Comment by exodist** [comment]
Another thing to note is that this is a problem with reading from SHM, there does not appear to be any issues with writing shm. Reading is a check to see if anything is pending, and it falls back to assuming there is pending stuff, so it is fine if the read fails.

For a problem like you are suggesting there would need to be an issue writing to shm, which would prevent things from noticing that things need to be read. A failure to write to SHM should be fatal, and we would be seeing that if there were pending events that could not be processed due to SHM writes not happening.

**Comment by exodist** [comment]
hmm, it looks like there is no success check on shmset :-(  that is probably bad, I will look into that....

**Comment by exodist** [comment]
Uploaded a new trial to CPAN with the SHM fixes (read failure does not produce a useless warning, but write failure is a fatal error)

**Comment by exodist** [comment]
*Note: I did not have time to write a test for the failure/fatal, but plan to do so before making a stable release.

**Comment by exodist** [comment]
@FGasper and @eserte are we seeing any SHM related failures with the latest trial release?

**Comment by FGasper** [comment]
@exodist I’ve never actually seen the issue locally, just run into it via CPAN Testers. :-/

**Comment by Leont** [comment]
> @FGasper and @eserte are we seeing any SHM related failures with the latest trial release?

Will CPAN Testers actually run trial version? I think most won't.

**Comment by exodist** [comment]
so one of those things that needs to be tested in prod?

**Comment by FGasper** [comment]
Is it possible to specify a trial release of Test::More in a trial release of another module?

**Comment by eserte** [comment]
> Will CPAN Testers actually run trial version of dependencies? I think most won't.

I can force a run of a couple of modules with the new trial. Maybe preferably choosing those modules which already had shm errors in the past...

**Comment by eserte** [comment]
Well I see a test failure with the trial itself (debian/jessie, perl 5.29.5, threaded build):
```
IPC shmwrite() failed (Invalid argument) this is a fatal error at /home/cpansand/.cpan/build/2018121720/Test-Simple-1.302146-0/blib/lib/Test2/API/Instance.pm line 456.
IPC shmwrite() failed (Invalid argument) this is a fatal error at /home/cpansand/.cpan/build/2018121720/Test-Simple-1.302146-0/blib/lib/Test2/API/Instance.pm line 456.
t/Test2/modules/API/Instance.t ................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 57 subtests passed 
```

**Comment by Leont** [comment]
> so one of those things that needs to be tested in prod?

I'd say writing a stress test is the more obvious approach.

**Comment by Leont** [comment]
> Well I see a test failure with the trial itself (debian/jessie, perl 5.29.5, threaded build):

Can you paste the output of the `ipcs` command on that machine?

**Comment by eserte** [comment]
@exodist: http://www.cpantesters.org/cpan/report/d0730c16-0239-11e9-97a2-cc5bebca8f1e
@Leont: `ipcs` and `ipcs -a` output is now empty (except for headers)

And now a test failure with Test-SharedFork-0.35, same machine, perl 5.28.1 (threaded):
```
IPC shmwrite() failed (Invalid argument) this is a fatal error at /home/cpansand/.cpan/build/2018121720/Test-Simple-1.302146-1/blib/lib/Test2/API/Instance.pm line 456.
# Looks like you planned 43 tests but ran 41.
t/01_simple.t ............ 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/43 subtests 
IPC shmwrite() failed (Invalid argument) this is a fatal error at /home/cpansand/.cpan/build/2018121720/Test-Simple-1.302146-1/blib/lib/Test2/API/Instance.pm line 456.
# Looks like you planned 43 tests but ran 25.
t/02_fork_method.t ....... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 18/43 subtests 
```

**Comment by exodist** [comment]
@eserte I just now uploaded Test-Simple-1.302147-TRIAL.tar.gz  which puts a bit more detail into the error message if you can run it again.

**Comment by exodist** [comment]
hmm, I may soon change that error message to be the equivalent of a confess instead of a croak....

**Comment by eserte** [comment]
The new trial, this time on a Ubuntu 16.04 system:
```
IPC shmwrite(22708224, '18121721/test2~10215~UggMJR/GLOBAL~10215~0~1~Test2~Event~Waiting', 0, 64) failed (Invalid argument) this is a fatal error at /home/cpansand/.cpan/build/2018121721/Test-Simple-1.302147-0/blib/lib/Test2/API.pm line 231.
IPC shmwrite(22708224, '18121721/test2~10215~UggMJR/GLOBAL~10215~0~2~Test2~Event~Waiting', 0, 64) failed (Invalid argument) this is a fatal error at /home/cpansand/.cpan/build/2018121721/Test-Simple-1.302147-0/blib/lib/Test2/API.pm line 231.
t/Test2/modules/API/Instance.t .................
Dubious, test returned 255 (wstat 65280, 0xff00)
All 54 subtests passed
```

**Comment by exodist** [comment]
ok, uploaded Test-Simple-1.302148-TRIAL.tar.gz which has the longmess from carp so I can get a full stack trace on those.

**Comment by eserte** [comment]
Here's one (no fail generated now, is this intended?):
```
IPC shmwrite(53018624, '18121721/test2~32607~LjTZur/GLOBAL~32607~0~1~Test2~Event~Waiting', 0, 64) failed (Invalid argument) this is a fatal error at /home/cpansand/.cpan/build/2018121721/Test-Simple-1.302148-4/blib/lib/Test2/API/Instance.pm line 456.
        Test2::API::Instance::set_ipc_pending(Test2::API::Instance=HASH(0x2316e98), "18121721/test2~32607~LjTZur/GLOBAL~32607~0~1~Test2~Event~Waiting") called at /home/cpansand/.cpan/build/2018121721/Test-Simple-1.302148-4/blib/lib/Test2/API.pm line 231
        Test2::API::test2_ipc_set_pending("18121721/test2~32607~LjTZur/GLOBAL~32607~0~1~Test2~Event~Waiting") called at /home/cpansand/.cpan/build/2018121721/Test-Simple-1.302148-4/blib/lib/Test2/IPC/Driver/Files.pm line 171
        Test2::IPC::Driver::Files::send(Test2::IPC::Driver::Files=HASH(0x26e86a8), "GLOBAL", Test2::Event::Waiting=HASH(0x2a75a78), "GLOBAL") called at /home/cpansand/.cpan/build/2018121721/Test-Simple-1.302148-4/blib/lib/Test2/IPC/Driver/Files.pm line 351
        Test2::IPC::Driver::Files::waiting(Test2::IPC::Driver::Files=HASH(0x26e86a8)) called at /home/cpansand/.cpan/build/2018121721/Test-Simple-1.302148-4/blib/lib/Test2/API/Instance.pm line 604
        Test2::API::Instance::set_exit(Test2::API::Instance=HASH(0x2316e98)) called at /home/cpansand/.cpan/build/2018121721/Test-Simple-1.302148-4/blib/lib/Test2/API.pm line 25
        Test2::API::END() called at t/Test2/behavior/ipc_wait_timeout.t line 0
        eval {...} called at t/Test2/behavior/ipc_wait_timeout.t line 0
Perl exited with active threads:
        1 running and unjoined
        0 finished and unjoined
        0 running and detached
```

**Comment by Leont** [comment]
The longmess doesn't give much information, because this is a cross process issue. Odds are that whatever goes wrong doesn't even happen in the process that prints the warning.

**Comment by exodist** [comment]
ok, I did a history dive, and I think I can mostly explain this:

Test2 does have a mechanism to make sure the parent does not exit before the children. It is a mechanism added in Test2, it was not present in Test::Builder or Test::SharedFork. I added this mechanism when I noticed that some Test::SharedFork and other tests that used forks/threads had no protection and often exited with success before a child process/thread was done, possibly masking errors.

When I added the protection mechanism I chose not to have it enabled when Test::SharedFork was active, it may also be disabled when Test::Builder is loaded. This decision was made to avoid introducing something new that nobody asked for that could cause errors that were not there previously. Most of said errors would be previously undetected real errors, but some tests that do really fancy IPC could fail from the new feature. I took the conservative "do not break anything new" approach by holding back the feature when not using pure Test2.

As I mentioned, Test::SharedFork disables this feature, so child procs can exit before the parent, and it assumes the developer of said tests "know what they are doing". Which brings us to the SHM error. The SHM optimization was added later. When the parent exits first the SHM is cleaned up resulting in these warnings. There is a race condition here based on how long it takes things to happen in each process. But ultimately, these errors in general show when a consumer of Test::SharedFork did not manage their processes properly. Technically this is not a new Test2 bug, it is Test2 exposing pre-existing bugs where it was possible for a child process to issue test events that were never seen by the parent.

The test2 test itself tests a lot of this logic, and messes with the variables that decide if test2 should wait for children, so in this case the test itself has a race condition I need to fix.

Now the question is how to move forward:
1) Always enable the Test2 logic to make sure the parent does not exit before the children. The downside here is we could break a few rare tests where people do their own IPC, do it correctly, and this behavior conflicts.
2) Make Test2 continue silently when the SHM is cleaned up due to the parent exiting first (IE preserve the old Test::SharedFork/Test::Builder behavior that could exit success even if a child was still running and reporting events)
3) Keep things as they are, but make the error it reports more informative announcing that the parent process was probably allowed to exit before the children, and that means there is a race condition in the tests process/thread management. Making it clear the test is at fault and needs to be fixed.

In either case the failing Test2 test needs to be fixed, but that is a "me" problem to solve.

**Comment by exodist** [comment]
@eserte I just uploaded Test-Simple-1.302149-TRIAL.tar.gz which makes the error message significantly more verbose with some useful info (pid/tid dumps). I would appreciate it if you had a chance to run this one again on your machine until the problems occurs so that I can inspect the updated error output.

**Comment by eserte** [comment]
One problem: with non-English locale and perl < 5.22 there are additional test errors (2×) now:
```
# Failed test 'Got exception when shm write fails (no tid/pid)'
# at t/Test2/modules/API/Instance.t line 558.
# GOT:      IPC shmwrite(-1, 'message', 0, 32) failed, this is a fatal error.
#   Error: (22) Ungültiges Argument
#   Parent  PID: ?
#   Current PID: 6264
#   Parent  TID: ?
#   Current TID: 0
#   IPC errors like this usually indicate a race condition in a test where the
#   parent thread/process is allowed to exit before all child processes/threads
#   are complete.
# EXPECTED: IPC shmwrite(-1, 'message', 0, 32) failed, this is a fatal error.
#   Error: (22) Invalid argument
#   Parent  PID: ?
#   Current PID: 6264
#   Parent  TID: ?
#   Current TID: 0
#   IPC errors like this usually indicate a race condition in a test where the
#   parent thread/process is allowed to exit before all child processes/threads
#   are complete.
```

**Comment by exodist** [comment]
I will fix that locale error, is it still possible to reproduce the shm problem, or do I need to fix this before that can happen?

**Comment by exodist** [comment]
Actually, just uploaded Test-Simple-1.302150-TRIAL.tar.gz  which fixes the locale issue.

**Comment by exodist** [comment]
oops, missed a locale issue, fixing now

**Comment by exodist** [comment]
Test-Simple-1.302151-TRIAL.tar.gz  now uploaded with both locale issues fixed.

**Comment by eserte** [comment]
Got one:
```
IPC shmwrite(97648658, '2018122019/test2~2238~Dq42cv/GLOBAL~2238~0~1~Test2~Event~Waiting', 0, 64) failed, this is a fatal error.
  Error: (22) Invalid argument
  Parent  PID: 2238
  Current PID: 2238
  Parent  TID: 0
  Current TID: 0
  IPC errors like this usually indicate a race condition in a test where the
  parent thread/process is allowed to exit before all child processes/threads
  are complete.
IPC shmwrite(97648658, '2018122019/test2~2238~Dq42cv/GLOBAL~2238~0~2~Test2~Event~Waiting', 0, 64) failed, this is a fatal error.
  Error: (22) Invalid argument
  Parent  PID: 2238
  Current PID: 2238
  Parent  TID: 0
  Current TID: 0
  IPC errors like this usually indicate a race condition in a test where the
  parent thread/process is allowed to exit before all child processes/threads
  are complete.
t/Test2/modules/API/Instance.t ................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 54 subtests passed 
```

**Comment by exodist** [comment]
@eserte those results confirm that this specific error is a bug in this test, and not likely due to IPC. Is it possible to use this version of Test2 to reproduce the original issue with the other module? My theory is that the other module will have different parent/current pid/tids.

**Comment by eserte** [comment]
Here's one with Test-SharedFork-0.35:
```
IPC shmwrite(91619329, 'test2~21202~Tny_Sp/21202~0~1545340099~1~21204~0~6~Test2~Event~Ok', 0, 64) failed, this is a fatal error.
  Error: (22) Invalid argument
  Parent  PID: 21202
  Current PID: 21204
  Parent  TID: 0
  Current TID: 0
  IPC errors like this usually indicate a race condition in a test where the
  parent thread/process is allowed to exit before all child processes/threads
  are complete.
# Looks like you planned 43 tests but ran 28.
t/01_simple.t ............ 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 15/43 subtests 
```

**Comment by exodist** [comment]
Test-Simple-1.302153-TRIAL.tar.gz has some additional changes to help debug this problem.
