### ISSUE TITLE
Consider making $STDOUT/$STDERR package variables

### ISSUE THREAD

**Issue by leonerd** [Test-More/test-more#822]
`Test2::API` takes itself a private clone of the STDOUT and STDERR filehandles, and uses only those for its output:

https://github.com/Test-More/test-more/blob/2fe36cff81a3faf18207a8f23ce38c38d9c3bac8/lib/Test2/API.pm#L150-L151

Because of this, it's impossible to use any functions based on those (e.g. `Test::More::diag()`) inside a forked child process, if the child process has closed those cloned filehandles.

When `IO::Async::Process` sets up a new forked child, it closes all filehandles other than STDIN/OUT/ERR and those it is explicitly told to keep. Therefore, this means that `diag()` is currently not useable from inside such a forked child process.

Were these variables simply changed from `my` to `our`, it would make them visible at the package level to other code, and these could be preserved by simply adding

```perl
setup => [
    keep => $Test2::API::STDOUT,
    keep => $Test2::API::STDERR,
    ...
]
```

to the constructor of an `IO::Async::Process`, telling it not to `close()` them in the child.

Would you accept such a change?

**Comment by exodist** [comment]
The example you gave indicates you just need the filehandle itself, not the variable it is stored in. Just below the API.pm lines you mentioned are 2 accessors that let you get the filehandles:

https://github.com/Test-More/test-more/blob/2fe36cff81a3faf18207a8f23ce38c38d9c3bac8/lib/Test2/API.pm#L150-L154

Can you use those accessors instead of directly using the variables?

**Comment by exodist** [comment]
No prob. Please come back and close the issue if that works.

**Comment by exodist** [comment]
I am going to close this. Feel free to re-open if you still have any trouble.
