### ISSUE TITLE
Suggesting on extending an API 

### ISSUE THREAD

**Issue by hurricup** [Test-More/test-more#828]
1. As far as I get it, assertion methods has the following API: assertion data + message (used as test name).
What do you think if i'll extend these methods with additional param - `$message_details` which could be used in case of failure. This data should be printed with diag message, after default one. 
Use case: I've added a test support for the IDE and there are features on IDE side which can't be supported with current API (well, they could, but would be better to make this available in the framework).
For example, IDE may show the diff window for expected/got pair. And if test provides expected data file path, you may adjust it from those diff window. So I could make something like `is('testline', 'expected data from file', 'test_name', " data_file: $file_path")` and get IDE support for updating test data.

2. Add some `--machine` option to use more machine friendly output, like escaping newlines and quotes in got/expected section of diagnostic.

**Comment by exodist** [comment]
So first off, great idea! It is already implemented in Test2::Suite which is essentially the successor to Test::More and where new features live.

Unfortunately it is not possible to make a similar change to Test::More, it would break backcompat in bad ways. Some people rely on the current prototype for ok/is/is_deeply, etc, and that would have to change. It would also require a bunch of changes to Test::Builder which will break things, specially libraries that monkeypatch it (quite a few, many are important).

Test2::Suite however has no such restrictions, and is based on Test2 which Test::Builder now wraps as a compatibility layer, which means full compatibility (or nearly so, a tiny handful of old libraries broke, but all are either unused, or have alternatives)

As for --machine, a command line flag is more likely something to put in the harness (prove, Test::Harness) or (yath, Test2::Harness).  Getting such a feature into prove is unlikely at this point, but Test2::Harness (yath) may already have what you want (but it is very experimental still)

Going to close this ticket since changing Test::More and Test::Builder in this way is not possible. If the feature you want is not actually what Test2::Suite offers please open a ticket there. Likewise on Test2::Harness! Those are where new features belong at this point, Test::More is practically unchangable due to legacy concerns.

**Comment by hurricup** [comment]
I understand compatibility issues, but additional methods could be introduced, with different prototype.
Concerning the `--machine`, yes, I've messed up, this more like an argument for prove, but this requires support from test results producer which could be implemented with some `$ENV` variable. Because atm it just prints expected text as it is. I'll check `Test2::Suite` thank you.

**Comment by exodist** [comment]
See https://metacpan.org/pod/Test2::Tools::Basic#ASSERTIONS

`ok($bool, $name, @diag)`

Most Test2::Suite tools follow the pattern of optional diagnostics at the end that are only reported on failure.


As for the --machine support in the test tools, Test2 + Test2::Harness make this possible via custom formatters, plugins, and similar that the harness can set. Test2::Harness in fact does by default make Test2 use a different formatter which reports extra details.
