### ISSUE TITLE
t/Test2/modules/Formatter/TAP.t should skip rather than fail when !AUTHOR_TESTING

### ISSUE THREAD

**Issue by FGasper** [Test-More/test-more#841]
I’m getting Travis CI failures on old Perls because Mojo won’t install because of too-old Test::More. When I try to rectify that by installing a fresh Test::More, though, I get a failure in t/Test2/modules/Formatter/TAP.t:
```
t/Test2/modules/Formatter/TAP.t ................ 1/? This test requires Term::Table to be installed, and must be run in AUTHOR_TESTING mode at t/Test2/modules/Formatter/TAP.t line 1022.

t/Test2/modules/Formatter/TAP.t ................ Dubious, test returned 2 (wstat 512, 0x200)
```
https://travis-ci.org/FGasper/p5-Net-Curl-Promiser/jobs/623423248

I can fix this via a force-install, but it also seems like something that the distribution ought to rectify?

Thank you!

**Comment by exodist** [comment]
There seems to be a misunderstanding here.

This only dies if you HAVE enabled AUTHOR_TESTING -AND- do not have Term::Table installed.

So, if you are not using AUTHOR_TESTING, the test will pass fine without Term::Table and simply skip those tests

Likewise if you have Term::Table, and do not use AUTHOR_TESTING this test will pass

There is only a fatal error if you enable AUTHOR_TESTING but do not have Term::Table installed.
This is completely intentional. AUTHOR_TESTING is intended to be a deeper set of tests to verify things the author (me) wants checked, but do not necessarily need to run for everyone else. I added this check specifically because a bug slipped by when I did not have Term::Table installed. I decided to make AUTHOR_TESTING (IE Testing intended to be more intense, and a higher standard than a regular cpan install) force you to have Term::Table installed to avoid letting such a big slip through in the future when I do my release testing.

This should not block the module from being installed under normal circumstances. You must have AUTHOR_TESTING turned on somehow.

The error message should be made more clear, the current wording does imply that the whole test file itself must be run under AUTHOR_TESTING and will fail otherwise, which is clearly ridiculous and not the message it should convey.

I will leave this ticket open until I fix the wording to something like this:
`"You are running this test under AUTHOR_TESTING, doing so requires Term::Table to be installed, but it is not currently installed, this is a fatal error. Please install Term::Table before attempting to run this test under AUTHOR_TESTING."`
