### ISSUE TITLE
done_testing without any tests returns 255

### ISSUE THREAD

**Issue by Leont** [Test-More/test-more#855]
`done_testing` without any tests (or `done_testing(0)` with tests) makes the test program return `255`.

I'm not entirely sure if this is a bug in the code, or something that should be documented, but I'm pretty sure one of them is true (at first sight I'd lean towards the former though).

**Comment by exodist** [comment]
Both are intentional. done_testing with no tests indicated a problem, an explicit skip_all is needed to have 0 tests. done_testing(0) is never valid as you would not be using done_testing, you would be using skip_all when you have 0 tests.


Note, this is how the behavior was specified when I looked into it, and mostly how things have always worked (bugs not withstanding). I could see a desire to make done_testing(0) cause a skip-all, but it currently does not provide a way to give a skip reason, and if I recall it has a prototype, so changing it could break things (I have to double check that).

**Comment by exodist** [comment]
double checked, it has no prototype, so it should be possible to make done_testing(0) and done_testing(0 => $reason) work without breaking things.
