### ISSUE TITLE
1.302186: missing dist tar ball

### ISSUE THREAD

**Issue by kloczek** [Test-More/test-more#885]
Looks like new version dist tart ball is missing on https://cpan.metacpan.org/modules/by-module/Test/
Does it mean that thi slocation will be from now not used?

**Comment by exodist** [comment]
This is apparently a metacpan bug, and has been reported to the right people by @jkeenan via email (I was cc'd). We can keep this issue open for now until metacpan fixes things though.

**Comment by jkeenan** [comment]
> This is apparently a metacpan bug, and has been reported to the right people by @jkeenan via email (I was cc'd). We can keep this issue open for now until metacpan fixes things though.

@exodist, Unfortunately I have not had good results so far. The perl.org admins do not believe the problem is in their bailiwick and have referred me either to modules@perl.org or pause-admin@perl.org.  I have not yet tried either.

Since the date you uploaded Test-Simple-1.302186 *other* distributions have been correctly uploaded and symlinked into `/modules/by-module/` -- Test-NoWarnings, for example.  So this is not a *general* failure of symlinking on CPAN.

My suggestion would be that you first go into the PAUSE interface and try *Utils/Force Reindexing*.  If, after 24 hours, that doesn't symlink 1.302186 into https://cpan.metacpan.org/modules/by-module/Test/, then send email to the addresses previously mentioned.

Thank you very much.
Jim Keenan

**Comment by exodist** [comment]
I force-re-indexed yesterday and now the tarball does appear to be in the right place.
