### ISSUE TITLE
Tests on Perl 5.8.9 fail from yesterday. (ubuntu-latest perl-5.8.9)

### ISSUE THREAD

**Issue by yuki-kimoto** [Test-More/test-more#920]
Tests on Perl 5.8.9 fail from yesterday.

```
Error: Variable "$formatter" is not imported at /home/runner/mylib/lib/perl5/Test2/API/Instance.pm line 128.
```

https://github.com/yuki-kimoto/SPVM-Sys/actions/runs/7028468637/job/19124472006

Do you know the reason?

**Comment by yuki-kimoto** [comment]
Thanks.

**Comment by briandfoy** [comment]
This is affecting my GitHub workflows, that are now failing because Test2 has problems on 5.008.

**Comment by exodist** [comment]
Sorry about that. I just use // and //= without thinking these days, but I will fix it.

**Comment by exodist** [comment]
@briandfoy I can only guess my last comment came across as flippant or dismissive, and I am sorry if that irritated you. I am also sorry for the trouble I caused with this release. I have a rigorous several hour process for releasing this module because of how important it is. This process involves installing and testing it against every perlbrew I have installed, and installing a good chunk of cpan, which takes several hours, where I investigate any/all failures of downstream modules to determine if I broke them, or if they were already broken.

Normally my system does catch and prevent breakages. This is the only module I have such a rigorous process on because of how important it is. This time some flaws were revealed in my process. For instance testing against all my perlbrews is not sufficient if I do not verify that I have at least 1 perlbrew for every major version, and given I got a new laptop recently, I did not have many perlbrews installed. This can and will be addressed and I will try to add something to my process to double check that all the necessary versions are checked.

I recently filtered github workflows from my email because on most of my projects they are just unreliable noise. I do not normally use or rely on them in favor of doing much more rigorous and complete testing that I control. It has probably been years since I paid attention to github workflows as at that time anything less than 5.16 seemed to be broken by default.

Once again, I am sorry that an issue slipped through the cracks in an otherwise rigorous process. I hope that my track record having maintained this dist for years with very few such bad releases, combined with my detailing of just how much I do care about verifying the release before it goes out, and my acknowledgement of this failure and steps to prevent similar in the future help ease your mind.
